name: PR Greeter
run-name: PR Greeter
on:
    pull_request:
        types: [ opened ]

jobs:
    Greetings:
        runs-on: ubuntu-latest
        steps:

            - name: Assign to reviewers
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.addAssignees({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        assignees: ['bykevinyang']
                    })

            - name: Label as submission
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ['Submission']
                    })
             
            - name: Greetings
              uses: actions/github-script@v5
              env:
                GITHUB_URL: ${{ github.event.pull_request.comments_url }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                script: |
                    echo "test"